### ISSUE TITLE
feature request: close nvim after closing last buffer

### ISSUE THREAD

**Issue by rudotriton** [kazhala/close-buffers.nvim#3]
hey, i'm looking for something that would optionally close neovim, when there is just one buffer open and i invoke a command to close it. do you think something like this would be in the scope of this project?

**Comment by kazhala** [comment]
Hi @rudotriton ,

This won't be in the scope of this project but you can achieve it via some simple logic in your own config. You can write a simple lua function in your config that checks if there's only a single visible buffer and if yes quit neovim otherwise just do buff delete.

some_module.lua
```lua
local M = {}

function M.delete_buffer()
  if #vim.fn.getbufinfo({buflisted = true}) == 1 then
    vim.cmd([[quit]])
  else
    require('close_buffers').delete({type = 'this'})
  end
end

return M
```

init.lua or some other lua file that get sourced
```lua
vim.api.nvim_set_keymap('n', '<leader>tc', [[<CMD>lua require('some_module').delete_buffer()<CR>]], {noremap = true})
```

The above are just some ideas (not tested might have typo), you can play around to make it suit your need.

Thanks,
Kevin
