### ISSUE TITLE
Close buffer given buffer number 

### ISSUE THREAD

**Issue by petertriho** [kazhala/close-buffers.nvim#4]
Would love to see a way to close buffers given a buffer number. Something like `BWipeout/BDelete <bufnr>`

**Comment by kazhala** [comment]
Hi @petertriho ,

Thanks for the issue. You can use `:bd <bufnr><CR>` or `:bw <bufnr><CR>` to delete a buffer based on a given buffer number.

Just thinking through the use-case atm, is it just for more coverage so that you can always rely on `BWipeout/BDelete` from `close-buffers` and not have to think about a different command?

Thanks,
Kevin

**Comment by petertriho** [comment]
@kazhala My use case is to use `BWipeout/BDelete` with [nvim-bufferline](https://github.com/akinsho/nvim-bufferline.lua) for the `close_command` and `right_mouse_command`. All good if you think it is out of scope as I still have `famiu/bufdelete.nvim` installed for it.

**Comment by kazhala** [comment]
Hi @petertriho , it make sense now (was not thinking about window layout or any extra stuff). I'll see what I could do to support it over the weekend.
